package com.orion.DigiWallet.jpaTest;
//REVIEW : JPA : 3

import jakarta.persistence.*;

import java.time.LocalDateTime;

@Entity
@Table(name = "employees")
public class Employee {

    //REVIEW : JPA : 4
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //strategy = GenerationType.IDENTITY means that the primary key value will be automatically generated by the database.
    //IDENTITY strategy is commonly used with databases that support auto-incrementing primary keys.
    // other strategies include AUTO, SEQUENCE, and TABLE.
    // auto : JPA provider will choose the appropriate strategy for the database.
    // sequence : uses a database sequence to generate primary key values.
    // table : uses a separate table to generate primary key values.
    private int id;

    //REVIEW : JPA : 5
    @Column(nullable = false, unique = true)
    private String name;

    @ManyToOne
    @JoinColumn(name = "department_id", nullable = false)
    private Department department;

//    @ManyToOne(fetch = FetchType.LAZY) in this case, the associated Department entity will be loaded from the database only when it is accessed for the first time.
//    @JoinColumn(name = "department_id")
//    private Department department;

//Employee emp = repo.findById(1).get();
// // session closed
//emp.getDepartment().getName(); // 💥 crash

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    @PreUpdate
    public void updateTimestamp() {
        this.updatedAt = LocalDateTime.now();
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    //prepersist is used to set the updatedAt field to the current date and time before the entity is persisted (inserted) into the database.
    //preupdate is used to set the updatedAt field to the current date and time before the entity is updated in the database.



}
